default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: threewygo

test:
  <<: *default
  database: threewygo_test

production:
  <<: *default
  database: threewygo_production
